export const BOOKING_CONSTANTS = {
  DURATIONS: {
    MIN: 30,
    MAX: 60,
  },
  CREDITS: {
    THIRTY_MINUTES: 1,
    SIXTY_MINUTES: 2,
  },
  MIN_ADVANCE_HOURS: 24,
  FULL_REFUND_HOURS: 24,
  PARTIAL_REFUND_HOURS: 12,
  PARTIAL_REFUND_PERCENTAGE: 0.5,
} as const;
